# server
server:
  port: 5505
  tomcat:
    max-threads: 50
    min-spare-threads: 20
  servlet:
    context-path: '/osbb'
    session:
      timeout: 30m

# spring
spring:
  application:
    name: '@project.artifactId@'

  # datasource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: '@flyway.url@'
    driver-class-name: org.mariadb.jdbc.Driver
    username: '@flyway.user@'
    password: '@flyway.password@'
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      minimumIdle: 2
      connectionTestQuery: SELECT version()

  # hibernate
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
